services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - json-server

  json-server:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./db.json:/app/db.json
    command: npx json-server@1.0.0-beta.15 --watch db.json --port 8080 --host 0.0.0.0
    ports:
      - "8080:8080"